//Emilie Eggleston
//9-29-00
//String Concatenation Program
//This program will output a message by assigning each letter as a variable

#include <iostream.h>
#include <conio.h>
#include <apstring.h>

void main(void)
{
clrscr();

//All my identifiers are letters
apstring
 a="A",
 c="C",
 d="D",
 e="E",
 g="G",
 h="H",
 i="I",
 k="K",
 l="L",
 n="N",
 o="O",
 r="R",
 s="S";

 //My final output that had to continue on another cout because of space
cout<<e+d+n+a<<" "<<h+i+g+h<<" "<<s+c+h+o+o;
cout<<l<<" "<<r+o+c+k+s<<endl;
}