#include <iostream.h>
#include <conio.h>
int main()
{clrscr();
cout<<"         EEEEEEEE\n         EEEEEEEE\n";
cout<<"         EEEEEEEE\n         EEE\n";
cout<<"         EEEEEE\n         EEEEEE\n         EEEEEE\n";
cout<<"         EEE\n         EEEEEEEE\n         EEEEEEEE\n";
cout<<"         EEEEEEEE\n";
cout<<"EEEEEEEE          HHH  HHH\nEEEEEEEE          HHH  HHH\n";
cout<<"EEEEEEEE          HHH  HHH\nEEE               HHH  HHH\n";
cout<<"EEEEEE            HHHHHHHH\nEEEEEE            HHHHHHHH\n";
cout<<"EEEEEE            HHHHHHHH\nEEE               HHH  HHH\n";
cout<<"EEEEEEEE          HHH  HHH\nEEEEEEEE          HHH  HHH\n";
cout<<"EEEEEEEE          HHH  HHH";
return 0;
}