#include <iostream.h>
//Miss Emilie Egghead
main()
{
cout<<"   ooo\n";
cout<<"  oo  o\n";
cout<<" o  o  o\n";
cout<<" o   o o\n";
cout<<"o       o\n";
cout<<"o  o o  o\n";
cout<<"o       o\n";
cout<<"o  o o  o\n";
cout<<" o  o  o\n";
cout<<"  o   o\n";
cout<<"   ooo\n";
cout<<" o  o  o\n";
cout<<"  o o o\n";
cout<<"   ooo\n";
cout<<"    o\n";
cout<<"   o o\n";
cout<<"  o   o\n";
cout<<" o     o\n";
cout<<"ooooooooo\n";
cout<<"   o o\n";
cout<<"   o o\n";
cout<<"   o o\n";
return 0;
}