//The Matrix

#include <iostream.h>
#include <conio.h>
#include <dos.h>

void main(void)
{
clrscr();

delay(3000);
cout<<"Wake up Neo.";
delay(7000);
clrscr();


delay(3000);
cout<<"T";
delay(900);
cout<<"h";
delay(1000);
cout<<"e ";
delay(900);
cout<<"M";
delay(750);
cout<<"a";
delay(500);
cout<<"t";
delay(500);
cout<<"r";
delay(750);
cout<<"i";
delay(750);
cout<<"x ";
delay(1000);
cout<<"h";
delay(500);
cout<<"a";
delay(500);
cout<<"s ";
delay(1000);
cout<<"y";
delay(750);
cout<<"o";
delay(750);
cout<<"u";
delay(1000);
cout<<".";
delay(1000);
cout<<".";
delay(1000);
cout<<".";
delay(5000);
clrscr();
delay(3000);

cout<<"Knock knock.";
delay(3000);
clrscr();
delay(1000);

cout<<"F";
delay(500);
cout<<"o";
delay(500);
cout<<"l";
delay(500);
cout<<"l";
delay(500);
cout<<"o";
delay(500);
cout<<"w";
delay(500);
cout<<" ";
delay(500);
cout<<"t";
delay(300);
cout<<"h";
delay(500);
cout<<"e";
delay(500);
cout<<" ";
delay(300);
cout<<"w";
delay(500);
cout<<"h";
delay(500);
cout<<"i";
delay(500);
cout<<"t";
delay(500);
cout<<"e";
delay(500);
cout<<" ";
delay(500);
cout<<"r";
delay(300);
cout<<"a";
delay(500);
cout<<"b";
delay(500);
cout<<"b";
delay(500);
cout<<"i";
delay(300);
cout<<"t";
delay(500);
cout<<".";
delay(5000);
}
